# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/Registration.proto\x12\x05proto\"\x93\x01\n\nSignUpInfo\x12\r\n\x05\x65mail\x18\x01 \x01(\x0c\x12\x10\n\x08username\x18\x02 \x01(\x0c\x12\x10\n\x08password\x18\x03 \x01(\x0c\x12\x17\n\x0fpasswordConfirm\x18\x04 \x01(\x0c\x12\x10\n\x08userType\x18\x05 \x01(\x0c\x12\x0f\n\x07\x61irline\x18\x06 \x01(\x0c\x12\x16\n\x0e\x63\x61rtaDiCredito\x18\x07 \x01(\x0c\"-\n\x0eSignUpResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\"7\n\x0eSignInResponse\x12\x12\n\nstoredType\x18\x01 \x01(\x0c\x12\x11\n\tisCorrect\x18\x02 \x01(\x08\",\n\x14GetLogFileRequestReg\x12\x14\n\x0cnumRichiesta\x18\x01 \x01(\x05\";\n\x12GetLogFileReplyReg\x12\x12\n\nchunk_file\x18\x01 \x01(\x0c\x12\x11\n\tnum_chunk\x18\x02 \x01(\x05\x32\xbf\x01\n\tUsersInfo\x12\x32\n\x06SignUp\x12\x11.proto.SignUpInfo\x1a\x15.proto.SignUpResponse\x12\x33\n\x06SignIn\x12\x12.proto.Credentials\x1a\x15.proto.SignInResponse\x12I\n\rgetLogFileReg\x12\x1b.proto.GetLogFileRequestReg\x1a\x19.proto.GetLogFileReplyReg0\x01\x62\x06proto3')



_SIGNUPINFO = DESCRIPTOR.message_types_by_name['SignUpInfo']
_SIGNUPRESPONSE = DESCRIPTOR.message_types_by_name['SignUpResponse']
_CREDENTIALS = DESCRIPTOR.message_types_by_name['Credentials']
_SIGNINRESPONSE = DESCRIPTOR.message_types_by_name['SignInResponse']
_GETLOGFILEREQUESTREG = DESCRIPTOR.message_types_by_name['GetLogFileRequestReg']
_GETLOGFILEREPLYREG = DESCRIPTOR.message_types_by_name['GetLogFileReplyReg']
SignUpInfo = _reflection.GeneratedProtocolMessageType('SignUpInfo', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPINFO,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.SignUpInfo)
  })
_sym_db.RegisterMessage(SignUpInfo)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.SignUpResponse)
  })
_sym_db.RegisterMessage(SignUpResponse)

Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

SignInResponse = _reflection.GeneratedProtocolMessageType('SignInResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINRESPONSE,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.SignInResponse)
  })
_sym_db.RegisterMessage(SignInResponse)

GetLogFileRequestReg = _reflection.GeneratedProtocolMessageType('GetLogFileRequestReg', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGFILEREQUESTREG,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetLogFileRequestReg)
  })
_sym_db.RegisterMessage(GetLogFileRequestReg)

GetLogFileReplyReg = _reflection.GeneratedProtocolMessageType('GetLogFileReplyReg', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGFILEREPLYREG,
  '__module__' : 'proto.Registration_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetLogFileReplyReg)
  })
_sym_db.RegisterMessage(GetLogFileReplyReg)

_USERSINFO = DESCRIPTOR.services_by_name['UsersInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNUPINFO._serialized_start=36
  _SIGNUPINFO._serialized_end=183
  _SIGNUPRESPONSE._serialized_start=185
  _SIGNUPRESPONSE._serialized_end=230
  _CREDENTIALS._serialized_start=232
  _CREDENTIALS._serialized_end=281
  _SIGNINRESPONSE._serialized_start=283
  _SIGNINRESPONSE._serialized_end=338
  _GETLOGFILEREQUESTREG._serialized_start=340
  _GETLOGFILEREQUESTREG._serialized_end=384
  _GETLOGFILEREPLYREG._serialized_start=386
  _GETLOGFILEREPLYREG._serialized_end=445
  _USERSINFO._serialized_start=448
  _USERSINFO._serialized_end=639
# @@protoc_insertion_point(module_scope)
