# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import Suggestions_pb2 as proto_dot_Suggestions__pb2


class SuggestionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSelectedFlight = channel.unary_unary(
                '/proto.SuggestionsService/GetSelectedFlight',
                request_serializer=proto_dot_Suggestions__pb2.SelectedFlight.SerializeToString,
                response_deserializer=proto_dot_Suggestions__pb2.SelectionResponse.FromString,
                )


class SuggestionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSelectedFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSelectedFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelectedFlight,
                    request_deserializer=proto_dot_Suggestions__pb2.SelectedFlight.FromString,
                    response_serializer=proto_dot_Suggestions__pb2.SelectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSelectedFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.SuggestionsService/GetSelectedFlight',
            proto_dot_Suggestions__pb2.SelectedFlight.SerializeToString,
            proto_dot_Suggestions__pb2.SelectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
