version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # - /etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    build: ./frontend
    user: root
    ports:
      - 5000:5000

  logging:
    build: ./logging
    user: root
  
  discovery:
    build: ./discovery
    user: root
    ports:
      - "50060-50061:50060"

  registration:
    build: ./registration
    user: root
    ports:
      - 50051:50051

  management:
    build: ./management
    user: root
    ports:
      - 50052:50052

  booking:
    build: ./booking
    user: root
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - 50053:50053
    depends_on:
      - rabbitmq

  payment:
    build: ./payment
    user: root
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - 50054:50054
    depends_on:
      - rabbitmq

  suggestions:
    build: ./suggestions
    user: root
    ports:
      - "50055-50056:50055"
