// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientToServer.proto

package server.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
