// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientToServer.proto

package server.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();
}
