# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Suggestions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/Suggestions.proto\x12\x05proto\"|\n\x0eSelectedFlight\x12\x13\n\x0b\x62ookingDate\x18\x01 \x01(\t\x12\x12\n\nflightDate\x18\x02 \x01(\t\x12\x0f\n\x07\x61irline\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65partureAirport\x18\x04 \x01(\t\x12\x16\n\x0e\x61rrivalAirport\x18\x05 \x01(\t\"4\n\x11SelectionResponse\x12\x1f\n\x17numDaysBeforeConvenient\x18\x01 \x01(\x05\x32Z\n\x12SuggestionsService\x12\x44\n\x11GetSelectedFlight\x12\x15.proto.SelectedFlight\x1a\x18.proto.SelectionResponseB\x11\n\rcontrol.protoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Suggestions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcontrol.protoP\001'
  _SELECTEDFLIGHT._serialized_start=34
  _SELECTEDFLIGHT._serialized_end=158
  _SELECTIONRESPONSE._serialized_start=160
  _SELECTIONRESPONSE._serialized_end=212
  _SUGGESTIONSSERVICE._serialized_start=214
  _SUGGESTIONSSERVICE._serialized_end=304
# @@protoc_insertion_point(module_scope)
