---
- hosts: all
  vars:
    local_app_dir: "/home/fanfa/Scrivania/Work in progress/progetto-SDCC/prove/ec2/gogo"
    remote_home: "/home/ec2-user"
    remote_app_dir: "{{remote_home}}/Scrivania/Work in progress/progetto-SDCC/prove/ec2/gogo"
    file_owner: ec2-user

  tasks:
    - name: copy application directory
      copy:
        src: "{{ local_app_dir }}/"
        dest: "{{ remote_app_dir }}"
      register: app  # save task output 

    - name: install golang
      become: yes # we need root privileges 
      yum:
        name: go
        state: present
     
    - name: modify .bashrc
      blockinfile:
        dest: "{{ remote_home }}/.bashrc"
        block: |
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH=$GOBIN:$PATH:/usr/local/go/bin
        marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
        insertafter: EOF
        create: yes 
        
    - name: install protobuf compiler
      become: yes # we need root privileges
      yum:
        name: protobuf-compiler
        state: present

    - name: copy systemd unit file
      become: yes 
      copy:
        src: "Gogo.service"
        dest: "/etc/systemd/system/"

    - name: enable and start systemd service
      become: yes 
      systemd:
        daemon_reload: yes
        state: restarted
        name: "Gogo.service"
        enabled: yes
      when: app.changed # only restart if new version was uploaded
