// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface DiscoveryServersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DiscoveryServers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string servers = 1;</code>
   */
  java.util.List<java.lang.String>
      getServersList();
  /**
   * <code>repeated string servers = 1;</code>
   */
  int getServersCount();
  /**
   * <code>repeated string servers = 1;</code>
   */
  java.lang.String getServers(int index);
  /**
   * <code>repeated string servers = 1;</code>
   */
  com.google.protobuf.ByteString
      getServersBytes(int index);
}
