// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public final class Discovery {
  private Discovery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_infoMicroservice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_infoMicroservice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_infoMicroservices_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_infoMicroservices_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_microserviceInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_microserviceInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_microserviceInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_microserviceInfoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DiscoveryServers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DiscoveryServers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PutReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PutReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Discovery.proto\022\005proto\"5\n\020infoMicroser" +
      "vice\022\023\n\013serviceName\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\"" +
      "H\n\021infoMicroservices\0223\n\022microservices_li" +
      "st\030\001 \003(\0132\027.proto.infoMicroservice\"J\n\027mic" +
      "roserviceInfoRequest\022/\n\rmicroservices\030\001 " +
      "\001(\0132\030.proto.infoMicroservices\"H\n\025microse" +
      "rviceInfoReply\022/\n\rmicroservices\030\001 \001(\0132\030." +
      "proto.infoMicroservices\"<\n\nGetRequest\022\023\n" +
      "\013serviceName\030\001 \001(\t\022\031\n\021serviceNameTarget\030" +
      "\002 \001(\t\"-\n\010GetReply\022\023\n\013serviceName\030\001 \001(\t\022\014" +
      "\n\004port\030\002 \001(\t\"/\n\nPutRequest\022\023\n\013serviceNam" +
      "e\030\001 \001(\t\022\014\n\004port\030\002 \001(\t\"#\n\020DiscoveryServer" +
      "s\022\017\n\007servers\030\001 \003(\t\"H\n\010PutReply\022\016\n\006result" +
      "\030\001 \001(\010\022,\n\013list_server\030\002 \001(\0132\027.proto.Disc" +
      "overyServers2\276\001\n\020DiscoveryService\022)\n\003get" +
      "\022\021.proto.GetRequest\032\017.proto.GetReply\022)\n\003" +
      "put\022\021.proto.PutRequest\032\017.proto.PutReply\022" +
      "T\n\024sendMicroserviceInfo\022\036.proto.microser" +
      "viceInfoRequest\032\034.proto.microserviceInfo" +
      "ReplyB\021\n\rcontrol.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_infoMicroservice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_infoMicroservice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_infoMicroservice_descriptor,
        new java.lang.String[] { "ServiceName", "Port", });
    internal_static_proto_infoMicroservices_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_infoMicroservices_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_infoMicroservices_descriptor,
        new java.lang.String[] { "MicroservicesList", });
    internal_static_proto_microserviceInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_microserviceInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_microserviceInfoRequest_descriptor,
        new java.lang.String[] { "Microservices", });
    internal_static_proto_microserviceInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_microserviceInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_microserviceInfoReply_descriptor,
        new java.lang.String[] { "Microservices", });
    internal_static_proto_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceNameTarget", });
    internal_static_proto_GetReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_GetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetReply_descriptor,
        new java.lang.String[] { "ServiceName", "Port", });
    internal_static_proto_PutRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_PutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PutRequest_descriptor,
        new java.lang.String[] { "ServiceName", "Port", });
    internal_static_proto_DiscoveryServers_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_DiscoveryServers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DiscoveryServers_descriptor,
        new java.lang.String[] { "Servers", });
    internal_static_proto_PutReply_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_PutReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PutReply_descriptor,
        new java.lang.String[] { "Result", "ListServer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
