// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface GetLogFileReplySugOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetLogFileReplySug)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes chunk_file = 1;</code>
   */
  com.google.protobuf.ByteString getChunkFile();

  /**
   * <code>int32 num_chunk = 2;</code>
   */
  int getNumChunk();
}
