// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface GetLogFileRequestSugOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetLogFileRequestSug)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numRichiesta = 1;</code>
   */
  int getNumRichiesta();
}
