// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface GetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string port = 2;</code>
   */
  java.lang.String getPort();
  /**
   * <code>string port = 2;</code>
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
