// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string serviceNameTarget = 2;</code>
   */
  java.lang.String getServiceNameTarget();
  /**
   * <code>string serviceNameTarget = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameTargetBytes();
}
