// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface infoMicroservicesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.infoMicroservices)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  java.util.List<control.proto.infoMicroservice> 
      getMicroservicesListList();
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  control.proto.infoMicroservice getMicroservicesList(int index);
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  int getMicroservicesListCount();
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  java.util.List<? extends control.proto.infoMicroserviceOrBuilder> 
      getMicroservicesListOrBuilderList();
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  control.proto.infoMicroserviceOrBuilder getMicroservicesListOrBuilder(
      int index);
}
