// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

/**
 * Protobuf type {@code proto.infoMicroservices}
 */
public  final class infoMicroservices extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.infoMicroservices)
    infoMicroservicesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use infoMicroservices.newBuilder() to construct.
  private infoMicroservices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private infoMicroservices() {
    microservicesList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private infoMicroservices(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              microservicesList_ = new java.util.ArrayList<control.proto.infoMicroservice>();
              mutable_bitField0_ |= 0x00000001;
            }
            microservicesList_.add(
                input.readMessage(control.proto.infoMicroservice.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        microservicesList_ = java.util.Collections.unmodifiableList(microservicesList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return control.proto.Discovery.internal_static_proto_infoMicroservices_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return control.proto.Discovery.internal_static_proto_infoMicroservices_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            control.proto.infoMicroservices.class, control.proto.infoMicroservices.Builder.class);
  }

  public static final int MICROSERVICES_LIST_FIELD_NUMBER = 1;
  private java.util.List<control.proto.infoMicroservice> microservicesList_;
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  public java.util.List<control.proto.infoMicroservice> getMicroservicesListList() {
    return microservicesList_;
  }
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  public java.util.List<? extends control.proto.infoMicroserviceOrBuilder> 
      getMicroservicesListOrBuilderList() {
    return microservicesList_;
  }
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  public int getMicroservicesListCount() {
    return microservicesList_.size();
  }
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  public control.proto.infoMicroservice getMicroservicesList(int index) {
    return microservicesList_.get(index);
  }
  /**
   * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
   */
  public control.proto.infoMicroserviceOrBuilder getMicroservicesListOrBuilder(
      int index) {
    return microservicesList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < microservicesList_.size(); i++) {
      output.writeMessage(1, microservicesList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < microservicesList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, microservicesList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof control.proto.infoMicroservices)) {
      return super.equals(obj);
    }
    control.proto.infoMicroservices other = (control.proto.infoMicroservices) obj;

    boolean result = true;
    result = result && getMicroservicesListList()
        .equals(other.getMicroservicesListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMicroservicesListCount() > 0) {
      hash = (37 * hash) + MICROSERVICES_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getMicroservicesListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static control.proto.infoMicroservices parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.infoMicroservices parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.infoMicroservices parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.infoMicroservices parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.infoMicroservices parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.infoMicroservices parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.infoMicroservices parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static control.proto.infoMicroservices parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static control.proto.infoMicroservices parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static control.proto.infoMicroservices parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static control.proto.infoMicroservices parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static control.proto.infoMicroservices parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(control.proto.infoMicroservices prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.infoMicroservices}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.infoMicroservices)
      control.proto.infoMicroservicesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return control.proto.Discovery.internal_static_proto_infoMicroservices_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return control.proto.Discovery.internal_static_proto_infoMicroservices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              control.proto.infoMicroservices.class, control.proto.infoMicroservices.Builder.class);
    }

    // Construct using control.proto.infoMicroservices.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMicroservicesListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (microservicesListBuilder_ == null) {
        microservicesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        microservicesListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return control.proto.Discovery.internal_static_proto_infoMicroservices_descriptor;
    }

    @java.lang.Override
    public control.proto.infoMicroservices getDefaultInstanceForType() {
      return control.proto.infoMicroservices.getDefaultInstance();
    }

    @java.lang.Override
    public control.proto.infoMicroservices build() {
      control.proto.infoMicroservices result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public control.proto.infoMicroservices buildPartial() {
      control.proto.infoMicroservices result = new control.proto.infoMicroservices(this);
      int from_bitField0_ = bitField0_;
      if (microservicesListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          microservicesList_ = java.util.Collections.unmodifiableList(microservicesList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.microservicesList_ = microservicesList_;
      } else {
        result.microservicesList_ = microservicesListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof control.proto.infoMicroservices) {
        return mergeFrom((control.proto.infoMicroservices)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(control.proto.infoMicroservices other) {
      if (other == control.proto.infoMicroservices.getDefaultInstance()) return this;
      if (microservicesListBuilder_ == null) {
        if (!other.microservicesList_.isEmpty()) {
          if (microservicesList_.isEmpty()) {
            microservicesList_ = other.microservicesList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMicroservicesListIsMutable();
            microservicesList_.addAll(other.microservicesList_);
          }
          onChanged();
        }
      } else {
        if (!other.microservicesList_.isEmpty()) {
          if (microservicesListBuilder_.isEmpty()) {
            microservicesListBuilder_.dispose();
            microservicesListBuilder_ = null;
            microservicesList_ = other.microservicesList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            microservicesListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMicroservicesListFieldBuilder() : null;
          } else {
            microservicesListBuilder_.addAllMessages(other.microservicesList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      control.proto.infoMicroservices parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (control.proto.infoMicroservices) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<control.proto.infoMicroservice> microservicesList_ =
      java.util.Collections.emptyList();
    private void ensureMicroservicesListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        microservicesList_ = new java.util.ArrayList<control.proto.infoMicroservice>(microservicesList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        control.proto.infoMicroservice, control.proto.infoMicroservice.Builder, control.proto.infoMicroserviceOrBuilder> microservicesListBuilder_;

    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public java.util.List<control.proto.infoMicroservice> getMicroservicesListList() {
      if (microservicesListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(microservicesList_);
      } else {
        return microservicesListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public int getMicroservicesListCount() {
      if (microservicesListBuilder_ == null) {
        return microservicesList_.size();
      } else {
        return microservicesListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public control.proto.infoMicroservice getMicroservicesList(int index) {
      if (microservicesListBuilder_ == null) {
        return microservicesList_.get(index);
      } else {
        return microservicesListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder setMicroservicesList(
        int index, control.proto.infoMicroservice value) {
      if (microservicesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicesListIsMutable();
        microservicesList_.set(index, value);
        onChanged();
      } else {
        microservicesListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder setMicroservicesList(
        int index, control.proto.infoMicroservice.Builder builderForValue) {
      if (microservicesListBuilder_ == null) {
        ensureMicroservicesListIsMutable();
        microservicesList_.set(index, builderForValue.build());
        onChanged();
      } else {
        microservicesListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder addMicroservicesList(control.proto.infoMicroservice value) {
      if (microservicesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicesListIsMutable();
        microservicesList_.add(value);
        onChanged();
      } else {
        microservicesListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder addMicroservicesList(
        int index, control.proto.infoMicroservice value) {
      if (microservicesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMicroservicesListIsMutable();
        microservicesList_.add(index, value);
        onChanged();
      } else {
        microservicesListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder addMicroservicesList(
        control.proto.infoMicroservice.Builder builderForValue) {
      if (microservicesListBuilder_ == null) {
        ensureMicroservicesListIsMutable();
        microservicesList_.add(builderForValue.build());
        onChanged();
      } else {
        microservicesListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder addMicroservicesList(
        int index, control.proto.infoMicroservice.Builder builderForValue) {
      if (microservicesListBuilder_ == null) {
        ensureMicroservicesListIsMutable();
        microservicesList_.add(index, builderForValue.build());
        onChanged();
      } else {
        microservicesListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder addAllMicroservicesList(
        java.lang.Iterable<? extends control.proto.infoMicroservice> values) {
      if (microservicesListBuilder_ == null) {
        ensureMicroservicesListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, microservicesList_);
        onChanged();
      } else {
        microservicesListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder clearMicroservicesList() {
      if (microservicesListBuilder_ == null) {
        microservicesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        microservicesListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public Builder removeMicroservicesList(int index) {
      if (microservicesListBuilder_ == null) {
        ensureMicroservicesListIsMutable();
        microservicesList_.remove(index);
        onChanged();
      } else {
        microservicesListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public control.proto.infoMicroservice.Builder getMicroservicesListBuilder(
        int index) {
      return getMicroservicesListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public control.proto.infoMicroserviceOrBuilder getMicroservicesListOrBuilder(
        int index) {
      if (microservicesListBuilder_ == null) {
        return microservicesList_.get(index);  } else {
        return microservicesListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public java.util.List<? extends control.proto.infoMicroserviceOrBuilder> 
         getMicroservicesListOrBuilderList() {
      if (microservicesListBuilder_ != null) {
        return microservicesListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(microservicesList_);
      }
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public control.proto.infoMicroservice.Builder addMicroservicesListBuilder() {
      return getMicroservicesListFieldBuilder().addBuilder(
          control.proto.infoMicroservice.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public control.proto.infoMicroservice.Builder addMicroservicesListBuilder(
        int index) {
      return getMicroservicesListFieldBuilder().addBuilder(
          index, control.proto.infoMicroservice.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.infoMicroservice microservices_list = 1;</code>
     */
    public java.util.List<control.proto.infoMicroservice.Builder> 
         getMicroservicesListBuilderList() {
      return getMicroservicesListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        control.proto.infoMicroservice, control.proto.infoMicroservice.Builder, control.proto.infoMicroserviceOrBuilder> 
        getMicroservicesListFieldBuilder() {
      if (microservicesListBuilder_ == null) {
        microservicesListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            control.proto.infoMicroservice, control.proto.infoMicroservice.Builder, control.proto.infoMicroserviceOrBuilder>(
                microservicesList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        microservicesList_ = null;
      }
      return microservicesListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.infoMicroservices)
  }

  // @@protoc_insertion_point(class_scope:proto.infoMicroservices)
  private static final control.proto.infoMicroservices DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new control.proto.infoMicroservices();
  }

  public static control.proto.infoMicroservices getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<infoMicroservices>
      PARSER = new com.google.protobuf.AbstractParser<infoMicroservices>() {
    @java.lang.Override
    public infoMicroservices parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new infoMicroservices(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<infoMicroservices> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<infoMicroservices> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public control.proto.infoMicroservices getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

