// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface microserviceInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.microserviceInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.infoMicroservices microservices = 1;</code>
   */
  boolean hasMicroservices();
  /**
   * <code>.proto.infoMicroservices microservices = 1;</code>
   */
  control.proto.infoMicroservices getMicroservices();
  /**
   * <code>.proto.infoMicroservices microservices = 1;</code>
   */
  control.proto.infoMicroservicesOrBuilder getMicroservicesOrBuilder();
}
