// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface OldFlightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.OldFlight)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string oldFlightsMsg = 1;</code>
   */
  java.lang.String getOldFlightsMsg();
  /**
   * <code>string oldFlightsMsg = 1;</code>
   */
  com.google.protobuf.ByteString
      getOldFlightsMsgBytes();
}
