// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

public interface PutReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PutReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  boolean hasListServer();
  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  control.proto.DiscoveryServers getListServer();
  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  control.proto.DiscoveryServersOrBuilder getListServerOrBuilder();
}
