// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package control.proto;

/**
 * <pre>
 *result:      risultato dell'esecuzione. Il metodo
 *ritorna TRUE se l'esecuzione è andata
 *a buon fine; altrimenti, ritorna FALSE.
 *list_server: Lista dei discovery server.
 * </pre>
 *
 * Protobuf type {@code proto.PutReply}
 */
public  final class PutReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.PutReply)
    PutReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PutReply.newBuilder() to construct.
  private PutReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PutReply() {
    result_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PutReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            result_ = input.readBool();
            break;
          }
          case 18: {
            control.proto.DiscoveryServers.Builder subBuilder = null;
            if (listServer_ != null) {
              subBuilder = listServer_.toBuilder();
            }
            listServer_ = input.readMessage(control.proto.DiscoveryServers.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(listServer_);
              listServer_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return control.proto.Discovery.internal_static_proto_PutReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return control.proto.Discovery.internal_static_proto_PutReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            control.proto.PutReply.class, control.proto.PutReply.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private boolean result_;
  /**
   * <code>bool result = 1;</code>
   */
  public boolean getResult() {
    return result_;
  }

  public static final int LIST_SERVER_FIELD_NUMBER = 2;
  private control.proto.DiscoveryServers listServer_;
  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  public boolean hasListServer() {
    return listServer_ != null;
  }
  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  public control.proto.DiscoveryServers getListServer() {
    return listServer_ == null ? control.proto.DiscoveryServers.getDefaultInstance() : listServer_;
  }
  /**
   * <code>.proto.DiscoveryServers list_server = 2;</code>
   */
  public control.proto.DiscoveryServersOrBuilder getListServerOrBuilder() {
    return getListServer();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != false) {
      output.writeBool(1, result_);
    }
    if (listServer_ != null) {
      output.writeMessage(2, getListServer());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, result_);
    }
    if (listServer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getListServer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof control.proto.PutReply)) {
      return super.equals(obj);
    }
    control.proto.PutReply other = (control.proto.PutReply) obj;

    boolean result = true;
    result = result && (getResult()
        == other.getResult());
    result = result && (hasListServer() == other.hasListServer());
    if (hasListServer()) {
      result = result && getListServer()
          .equals(other.getListServer());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getResult());
    if (hasListServer()) {
      hash = (37 * hash) + LIST_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getListServer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static control.proto.PutReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.PutReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.PutReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.PutReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.PutReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static control.proto.PutReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static control.proto.PutReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static control.proto.PutReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static control.proto.PutReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static control.proto.PutReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static control.proto.PutReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static control.proto.PutReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(control.proto.PutReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *result:      risultato dell'esecuzione. Il metodo
   *ritorna TRUE se l'esecuzione è andata
   *a buon fine; altrimenti, ritorna FALSE.
   *list_server: Lista dei discovery server.
   * </pre>
   *
   * Protobuf type {@code proto.PutReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.PutReply)
      control.proto.PutReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return control.proto.Discovery.internal_static_proto_PutReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return control.proto.Discovery.internal_static_proto_PutReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              control.proto.PutReply.class, control.proto.PutReply.Builder.class);
    }

    // Construct using control.proto.PutReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = false;

      if (listServerBuilder_ == null) {
        listServer_ = null;
      } else {
        listServer_ = null;
        listServerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return control.proto.Discovery.internal_static_proto_PutReply_descriptor;
    }

    @java.lang.Override
    public control.proto.PutReply getDefaultInstanceForType() {
      return control.proto.PutReply.getDefaultInstance();
    }

    @java.lang.Override
    public control.proto.PutReply build() {
      control.proto.PutReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public control.proto.PutReply buildPartial() {
      control.proto.PutReply result = new control.proto.PutReply(this);
      result.result_ = result_;
      if (listServerBuilder_ == null) {
        result.listServer_ = listServer_;
      } else {
        result.listServer_ = listServerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof control.proto.PutReply) {
        return mergeFrom((control.proto.PutReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(control.proto.PutReply other) {
      if (other == control.proto.PutReply.getDefaultInstance()) return this;
      if (other.getResult() != false) {
        setResult(other.getResult());
      }
      if (other.hasListServer()) {
        mergeListServer(other.getListServer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      control.proto.PutReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (control.proto.PutReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean result_ ;
    /**
     * <code>bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }
    /**
     * <code>bool result = 1;</code>
     */
    public Builder setResult(boolean value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool result = 1;</code>
     */
    public Builder clearResult() {
      
      result_ = false;
      onChanged();
      return this;
    }

    private control.proto.DiscoveryServers listServer_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        control.proto.DiscoveryServers, control.proto.DiscoveryServers.Builder, control.proto.DiscoveryServersOrBuilder> listServerBuilder_;
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public boolean hasListServer() {
      return listServerBuilder_ != null || listServer_ != null;
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public control.proto.DiscoveryServers getListServer() {
      if (listServerBuilder_ == null) {
        return listServer_ == null ? control.proto.DiscoveryServers.getDefaultInstance() : listServer_;
      } else {
        return listServerBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public Builder setListServer(control.proto.DiscoveryServers value) {
      if (listServerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        listServer_ = value;
        onChanged();
      } else {
        listServerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public Builder setListServer(
        control.proto.DiscoveryServers.Builder builderForValue) {
      if (listServerBuilder_ == null) {
        listServer_ = builderForValue.build();
        onChanged();
      } else {
        listServerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public Builder mergeListServer(control.proto.DiscoveryServers value) {
      if (listServerBuilder_ == null) {
        if (listServer_ != null) {
          listServer_ =
            control.proto.DiscoveryServers.newBuilder(listServer_).mergeFrom(value).buildPartial();
        } else {
          listServer_ = value;
        }
        onChanged();
      } else {
        listServerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public Builder clearListServer() {
      if (listServerBuilder_ == null) {
        listServer_ = null;
        onChanged();
      } else {
        listServer_ = null;
        listServerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public control.proto.DiscoveryServers.Builder getListServerBuilder() {
      
      onChanged();
      return getListServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    public control.proto.DiscoveryServersOrBuilder getListServerOrBuilder() {
      if (listServerBuilder_ != null) {
        return listServerBuilder_.getMessageOrBuilder();
      } else {
        return listServer_ == null ?
            control.proto.DiscoveryServers.getDefaultInstance() : listServer_;
      }
    }
    /**
     * <code>.proto.DiscoveryServers list_server = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        control.proto.DiscoveryServers, control.proto.DiscoveryServers.Builder, control.proto.DiscoveryServersOrBuilder> 
        getListServerFieldBuilder() {
      if (listServerBuilder_ == null) {
        listServerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            control.proto.DiscoveryServers, control.proto.DiscoveryServers.Builder, control.proto.DiscoveryServersOrBuilder>(
                getListServer(),
                getParentForChildren(),
                isClean());
        listServer_ = null;
      }
      return listServerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.PutReply)
  }

  // @@protoc_insertion_point(class_scope:proto.PutReply)
  private static final control.proto.PutReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new control.proto.PutReply();
  }

  public static control.proto.PutReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PutReply>
      PARSER = new com.google.protobuf.AbstractParser<PutReply>() {
    @java.lang.Override
    public PutReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PutReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PutReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PutReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public control.proto.PutReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

