// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface SelectedFlightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SelectedFlight)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookingDate = 1;</code>
   */
  java.lang.String getBookingDate();
  /**
   * <code>string bookingDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getBookingDateBytes();

  /**
   * <code>string flightDate = 2;</code>
   */
  java.lang.String getFlightDate();
  /**
   * <code>string flightDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getFlightDateBytes();

  /**
   * <code>string airline = 3;</code>
   */
  java.lang.String getAirline();
  /**
   * <code>string airline = 3;</code>
   */
  com.google.protobuf.ByteString
      getAirlineBytes();

  /**
   * <code>string departureAirport = 4;</code>
   */
  java.lang.String getDepartureAirport();
  /**
   * <code>string departureAirport = 4;</code>
   */
  com.google.protobuf.ByteString
      getDepartureAirportBytes();

  /**
   * <code>string arrivalAirport = 5;</code>
   */
  java.lang.String getArrivalAirport();
  /**
   * <code>string arrivalAirport = 5;</code>
   */
  com.google.protobuf.ByteString
      getArrivalAirportBytes();
}
