// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface SelectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SelectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numDaysBeforeConvenient = 1;</code>
   */
  int getNumDaysBeforeConvenient();
}
