// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public interface StoreOldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StoreOldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isOk = 1;</code>
   */
  boolean getIsOk();
}
