// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Suggestions.proto

package control.proto;

public final class Suggestions {
  private Suggestions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SelectedFlight_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SelectedFlight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SelectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SelectionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Suggestions.proto\022\005proto\"|\n\016SelectedFl" +
      "ight\022\023\n\013bookingDate\030\001 \001(\t\022\022\n\nflightDate\030" +
      "\002 \001(\t\022\017\n\007airline\030\003 \001(\t\022\030\n\020departureAirpo" +
      "rt\030\004 \001(\t\022\026\n\016arrivalAirport\030\005 \001(\t\"4\n\021Sele" +
      "ctionResponse\022\037\n\027numDaysBeforeConvenient" +
      "\030\001 \001(\0052Z\n\022SuggestionsService\022D\n\021GetSelec" +
      "tedFlight\022\025.proto.SelectedFlight\032\030.proto" +
      ".SelectionResponseB\021\n\rcontrol.protoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_SelectedFlight_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SelectedFlight_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SelectedFlight_descriptor,
        new java.lang.String[] { "BookingDate", "FlightDate", "Airline", "DepartureAirport", "ArrivalAirport", });
    internal_static_proto_SelectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SelectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SelectionResponse_descriptor,
        new java.lang.String[] { "NumDaysBeforeConvenient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
