# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/Payment.proto\x12\x05proto\"\xc7\x02\n\nNewPayment\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06idVolo\x18\x02 \x01(\t\x12\x15\n\rselectedSeats\x18\x03 \x03(\t\x12\x13\n\x0bpaymentDate\x18\x04 \x01(\t\x12\x11\n\tbasePrice\x18\x05 \x01(\t\x12\x12\n\nseatsPrice\x18\x06 \x01(\t\x12\x15\n\rservicesPrice\x18\x07 \x01(\t\x12\x12\n\ntotalPrice\x18\x08 \x01(\t\x12\x14\n\x0cnumStivaMedi\x18\t \x01(\x05\x12\x16\n\x0enumStivaGrandi\x18\n \x01(\x05\x12\x1a\n\x12numBagagliSpeciali\x18\x0b \x01(\x05\x12\x18\n\x10numAssicurazioni\x18\x0c \x01(\x05\x12\x12\n\nnumAnimali\x18\r \x01(\x05\x12\x12\n\nnumNeonati\x18\x0e \x01(\x05\x12\r\n\x05\x65mail\x18\x0f \x01(\t\"\x1b\n\x0bPayResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\",\n\x14GetLogFileRequestPay\x12\x14\n\x0cnumRichiesta\x18\x01 \x01(\x05\";\n\x12GetLogFileReplyPay\x12\x12\n\nchunk_file\x18\x01 \x01(\x0c\x12\x11\n\tnum_chunk\x18\x02 \x01(\x05\x32\x85\x01\n\x03Pay\x12\x33\n\nAddPayment\x12\x11.proto.NewPayment\x1a\x12.proto.PayResponse\x12I\n\rgetLogFilePay\x12\x1b.proto.GetLogFileRequestPay\x1a\x19.proto.GetLogFileReplyPay0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWPAYMENT._serialized_start=31
  _NEWPAYMENT._serialized_end=358
  _PAYRESPONSE._serialized_start=360
  _PAYRESPONSE._serialized_end=387
  _GETLOGFILEREQUESTPAY._serialized_start=389
  _GETLOGFILEREQUESTPAY._serialized_end=433
  _GETLOGFILEREPLYPAY._serialized_start=435
  _GETLOGFILEREPLYPAY._serialized_end=494
  _PAY._serialized_start=497
  _PAY._serialized_end=630
# @@protoc_insertion_point(module_scope)
