version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build: ./producer
    user: root
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - "50100:50100"
    depends_on:
      - rabbitmq

  client:
    build: ./consumer
    user: root
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - "50101:50101"
    depends_on:
      - rabbitmq
