# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/FroMan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/FroMan.proto\x12\x05proto\"\x1e\n\x0cPriceRequest\x12\x0e\n\x06idVolo\x18\x01 \x01(\t\"\x1b\n\nPriceReply\x12\r\n\x05price\x18\x01 \x01(\t\"\xb2\x01\n\tNewFlight\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65partureAirport\x18\x03 \x01(\t\x12\x16\n\x0e\x61rrivalAirport\x18\x04 \x01(\t\x12\x15\n\rdepartureTime\x18\x05 \x01(\t\x12\x13\n\x0b\x61rrivalTime\x18\x06 \x01(\t\x12\x0f\n\x07\x61irline\x18\x07 \x01(\t\x12\r\n\x05price\x18\x08 \x01(\t\x12\r\n\x05seats\x18\t \x01(\x05\"\x1b\n\x0b\x41\x64\x64Response\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"3\n\rUpdatedFlight\x12\x10\n\x08\x66lightId\x18\x01 \x01(\t\x12\x10\n\x08newPrice\x18\x02 \x01(\t\"!\n\x11ModFlightResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"q\n\x0cUpdatedSeats\x12\x0f\n\x07\x61irline\x18\x01 \x01(\t\x12\x0e\n\x06price1\x18\x02 \x01(\t\x12\x0e\n\x06price2\x18\x03 \x01(\t\x12\x0e\n\x06price6\x18\x04 \x01(\t\x12\x0f\n\x07price16\x18\x05 \x01(\t\x12\x0f\n\x07price18\x18\x06 \x01(\t\" \n\x10ModSeatsResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"\x88\x01\n\x0fUpdatedServices\x12\x0f\n\x07\x61irline\x18\x01 \x01(\t\x12\x0f\n\x07priceBM\x18\x02 \x01(\t\x12\x0f\n\x07priceBG\x18\x03 \x01(\t\x12\x0f\n\x07priceBS\x18\x04 \x01(\t\x12\x0f\n\x07priceAD\x18\x05 \x01(\t\x12\x0f\n\x07priceAB\x18\x06 \x01(\t\x12\x0f\n\x07priceTN\x18\x07 \x01(\t\"#\n\x13ModServicesResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\x32\xbd\x02\n\x0b\x46lightsInfo\x12\x31\n\tAddFlight\x12\x10.proto.NewFlight\x1a\x12.proto.AddResponse\x12>\n\x0cModifyFlight\x12\x14.proto.UpdatedFlight\x1a\x18.proto.ModFlightResponse\x12;\n\x0bModifySeats\x12\x13.proto.UpdatedSeats\x1a\x17.proto.ModSeatsResponse\x12\x44\n\x0eModifyServices\x12\x16.proto.UpdatedServices\x1a\x1a.proto.ModServicesResponse\x12\x38\n\x0eGetPriceFlight\x12\x13.proto.PriceRequest\x1a\x11.proto.PriceReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.FroMan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICEREQUEST._serialized_start=29
  _PRICEREQUEST._serialized_end=59
  _PRICEREPLY._serialized_start=61
  _PRICEREPLY._serialized_end=88
  _NEWFLIGHT._serialized_start=91
  _NEWFLIGHT._serialized_end=269
  _ADDRESPONSE._serialized_start=271
  _ADDRESPONSE._serialized_end=298
  _UPDATEDFLIGHT._serialized_start=300
  _UPDATEDFLIGHT._serialized_end=351
  _MODFLIGHTRESPONSE._serialized_start=353
  _MODFLIGHTRESPONSE._serialized_end=386
  _UPDATEDSEATS._serialized_start=388
  _UPDATEDSEATS._serialized_end=501
  _MODSEATSRESPONSE._serialized_start=503
  _MODSEATSRESPONSE._serialized_end=535
  _UPDATEDSERVICES._serialized_start=538
  _UPDATEDSERVICES._serialized_end=674
  _MODSERVICESRESPONSE._serialized_start=676
  _MODSERVICESRESPONSE._serialized_end=711
  _FLIGHTSINFO._serialized_start=714
  _FLIGHTSINFO._serialized_end=1031
# @@protoc_insertion_point(module_scope)
