# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import Managment_pb2 as proto_dot_Managment__pb2


class FlightsInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFlight = channel.unary_unary(
                '/proto.FlightsInfo/AddFlight',
                request_serializer=proto_dot_Managment__pb2.NewFlight.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.AddResponse.FromString,
                )
        self.ModifyFlight = channel.unary_unary(
                '/proto.FlightsInfo/ModifyFlight',
                request_serializer=proto_dot_Managment__pb2.UpdatedFlight.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.ModFlightResponse.FromString,
                )
        self.ModifySeats = channel.unary_unary(
                '/proto.FlightsInfo/ModifySeats',
                request_serializer=proto_dot_Managment__pb2.UpdatedSeats.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.ModSeatsResponse.FromString,
                )
        self.ModifyServices = channel.unary_unary(
                '/proto.FlightsInfo/ModifyServices',
                request_serializer=proto_dot_Managment__pb2.UpdatedServices.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.ModServicesResponse.FromString,
                )
        self.GetPriceFlight = channel.unary_unary(
                '/proto.FlightsInfo/GetPriceFlight',
                request_serializer=proto_dot_Managment__pb2.PriceRequest.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.PriceReply.FromString,
                )
        self.GetAllSeatsFlight = channel.unary_stream(
                '/proto.FlightsInfo/GetAllSeatsFlight',
                request_serializer=proto_dot_Managment__pb2.SeatCostRequest.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.SeatCostReply.FromString,
                )
        self.GetAlladditionalServicesFlight = channel.unary_stream(
                '/proto.FlightsInfo/GetAlladditionalServicesFlight',
                request_serializer=proto_dot_Managment__pb2.AdditionalServiceCostRequest.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.AdditionalServiceCostReply.FromString,
                )
        self.getLogFileMan = channel.unary_stream(
                '/proto.FlightsInfo/getLogFileMan',
                request_serializer=proto_dot_Managment__pb2.GetLogFileRequestMan.SerializeToString,
                response_deserializer=proto_dot_Managment__pb2.GetLogFileReplyMan.FromString,
                )


class FlightsInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifySeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSeatsFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlladditionalServicesFlight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLogFileMan(self, request, context):
        """Logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightsInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFlight,
                    request_deserializer=proto_dot_Managment__pb2.NewFlight.FromString,
                    response_serializer=proto_dot_Managment__pb2.AddResponse.SerializeToString,
            ),
            'ModifyFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyFlight,
                    request_deserializer=proto_dot_Managment__pb2.UpdatedFlight.FromString,
                    response_serializer=proto_dot_Managment__pb2.ModFlightResponse.SerializeToString,
            ),
            'ModifySeats': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifySeats,
                    request_deserializer=proto_dot_Managment__pb2.UpdatedSeats.FromString,
                    response_serializer=proto_dot_Managment__pb2.ModSeatsResponse.SerializeToString,
            ),
            'ModifyServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyServices,
                    request_deserializer=proto_dot_Managment__pb2.UpdatedServices.FromString,
                    response_serializer=proto_dot_Managment__pb2.ModServicesResponse.SerializeToString,
            ),
            'GetPriceFlight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceFlight,
                    request_deserializer=proto_dot_Managment__pb2.PriceRequest.FromString,
                    response_serializer=proto_dot_Managment__pb2.PriceReply.SerializeToString,
            ),
            'GetAllSeatsFlight': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllSeatsFlight,
                    request_deserializer=proto_dot_Managment__pb2.SeatCostRequest.FromString,
                    response_serializer=proto_dot_Managment__pb2.SeatCostReply.SerializeToString,
            ),
            'GetAlladditionalServicesFlight': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAlladditionalServicesFlight,
                    request_deserializer=proto_dot_Managment__pb2.AdditionalServiceCostRequest.FromString,
                    response_serializer=proto_dot_Managment__pb2.AdditionalServiceCostReply.SerializeToString,
            ),
            'getLogFileMan': grpc.unary_stream_rpc_method_handler(
                    servicer.getLogFileMan,
                    request_deserializer=proto_dot_Managment__pb2.GetLogFileRequestMan.FromString,
                    response_serializer=proto_dot_Managment__pb2.GetLogFileReplyMan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.FlightsInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlightsInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FlightsInfo/AddFlight',
            proto_dot_Managment__pb2.NewFlight.SerializeToString,
            proto_dot_Managment__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FlightsInfo/ModifyFlight',
            proto_dot_Managment__pb2.UpdatedFlight.SerializeToString,
            proto_dot_Managment__pb2.ModFlightResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifySeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FlightsInfo/ModifySeats',
            proto_dot_Managment__pb2.UpdatedSeats.SerializeToString,
            proto_dot_Managment__pb2.ModSeatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FlightsInfo/ModifyServices',
            proto_dot_Managment__pb2.UpdatedServices.SerializeToString,
            proto_dot_Managment__pb2.ModServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPriceFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.FlightsInfo/GetPriceFlight',
            proto_dot_Managment__pb2.PriceRequest.SerializeToString,
            proto_dot_Managment__pb2.PriceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllSeatsFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.FlightsInfo/GetAllSeatsFlight',
            proto_dot_Managment__pb2.SeatCostRequest.SerializeToString,
            proto_dot_Managment__pb2.SeatCostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAlladditionalServicesFlight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.FlightsInfo/GetAlladditionalServicesFlight',
            proto_dot_Managment__pb2.AdditionalServiceCostRequest.SerializeToString,
            proto_dot_Managment__pb2.AdditionalServiceCostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getLogFileMan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.FlightsInfo/getLogFileMan',
            proto_dot_Managment__pb2.GetLogFileRequestMan.SerializeToString,
            proto_dot_Managment__pb2.GetLogFileReplyMan.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
