# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import m1_to_m2_pb2 as proto_dot_m1__to__m2__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getServiceName = channel.unary_unary(
                '/proto.Greeter/getServiceName',
                request_serializer=proto_dot_m1__to__m2__pb2.request.SerializeToString,
                response_deserializer=proto_dot_m1__to__m2__pb2.response.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getServiceName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getServiceName': grpc.unary_unary_rpc_method_handler(
                    servicer.getServiceName,
                    request_deserializer=proto_dot_m1__to__m2__pb2.request.FromString,
                    response_serializer=proto_dot_m1__to__m2__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getServiceName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Greeter/getServiceName',
            proto_dot_m1__to__m2__pb2.request.SerializeToString,
            proto_dot_m1__to__m2__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
