# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/m1_to_m2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/m1_to_m2.proto\x12\x05proto\"#\n\x07request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x08response\x12\x13\n\x0bserviceName\x18\x01 \x01(\t2<\n\x07Greeter\x12\x31\n\x0egetServiceName\x12\x0e.proto.request\x1a\x0f.proto.responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto.m1_to_m2_pb2'
  # @@protoc_insertion_point(class_scope:proto.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.m1_to_m2_pb2'
  # @@protoc_insertion_point(class_scope:proto.response)
  })
_sym_db.RegisterMessage(response)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=31
  _REQUEST._serialized_end=66
  _RESPONSE._serialized_start=68
  _RESPONSE._serialized_end=99
  _GREETER._serialized_start=101
  _GREETER._serialized_end=161
# @@protoc_insertion_point(module_scope)
