// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientToServer.proto

package client.proto;

public final class ClientToServer {
  private ClientToServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resources_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resources_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resources_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resources_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ClientToServer.proto\022\tresources\"#\n\007Req" +
      "uest\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"\037\n\010Respon" +
      "se\022\023\n\013serviceName\030\001 \001(\t2D\n\007Greeter\0229\n\016Ge" +
      "tServiceName\022\022.resources.Request\032\023.resou" +
      "rces.ResponseB\020\n\014client.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_resources_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_resources_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resources_Request_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_resources_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_resources_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resources_Response_descriptor,
        new java.lang.String[] { "ServiceName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
