# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Boo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tBoo.proto\x12\x05proto\"\x8b\x01\n\x14getAllFlightsRequest\x12\x0e\n\x06giorno\x18\x01 \x01(\x05\x12\x0c\n\x04mese\x18\x02 \x01(\x05\x12\x0c\n\x04\x61nno\x18\x03 \x01(\x05\x12\x19\n\x11\x61\x65reoporto_arrivo\x18\x04 \x01(\t\x12\x1b\n\x13\x61\x65reoporto_partenza\x18\x05 \x01(\t\x12\x0f\n\x07persone\x18\x06 \x01(\x05\"3\n\x12getAllFlightsReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tcompagnia\x18\x02 \x01(\t2Y\n\x0e\x42ookingService\x12G\n\rgetAllFlights\x12\x1b.proto.getAllFlightsRequest\x1a\x19.proto.getAllFlightsReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Boo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETALLFLIGHTSREQUEST._serialized_start=21
  _GETALLFLIGHTSREQUEST._serialized_end=160
  _GETALLFLIGHTSREPLY._serialized_start=162
  _GETALLFLIGHTSREPLY._serialized_end=213
  _BOOKINGSERVICE._serialized_start=215
  _BOOKINGSERVICE._serialized_end=304
# @@protoc_insertion_point(module_scope)
