# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/BooMan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/BooMan.proto\x12\x05proto\"\x17\n\tIdMessage\x12\n\n\x02id\x18\x01 \x01(\t\"\x1a\n\nIdResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"\xb3\x01\n\nNewFlight2\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65partureAirport\x18\x03 \x01(\t\x12\x16\n\x0e\x61rrivalAirport\x18\x04 \x01(\t\x12\x15\n\rdepartureTime\x18\x05 \x01(\t\x12\x13\n\x0b\x61rrivalTime\x18\x06 \x01(\t\x12\x0f\n\x07\x61irline\x18\x07 \x01(\t\x12\r\n\x05price\x18\x08 \x01(\t\x12\r\n\x05seats\x18\t \x01(\x05\" \n\x10RegisterResponse\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\x32\x7f\n\x10\x46lightsAndPrices\x12-\n\x06SendId\x12\x10.proto.IdMessage\x1a\x11.proto.IdResponse\x12<\n\x0eRegisterFlight\x12\x11.proto.NewFlight2\x1a\x17.proto.RegisterResponseb\x06proto3')



_IDMESSAGE = DESCRIPTOR.message_types_by_name['IdMessage']
_IDRESPONSE = DESCRIPTOR.message_types_by_name['IdResponse']
_NEWFLIGHT2 = DESCRIPTOR.message_types_by_name['NewFlight2']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
IdMessage = _reflection.GeneratedProtocolMessageType('IdMessage', (_message.Message,), {
  'DESCRIPTOR' : _IDMESSAGE,
  '__module__' : 'proto.BooMan_pb2'
  # @@protoc_insertion_point(class_scope:proto.IdMessage)
  })
_sym_db.RegisterMessage(IdMessage)

IdResponse = _reflection.GeneratedProtocolMessageType('IdResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDRESPONSE,
  '__module__' : 'proto.BooMan_pb2'
  # @@protoc_insertion_point(class_scope:proto.IdResponse)
  })
_sym_db.RegisterMessage(IdResponse)

NewFlight2 = _reflection.GeneratedProtocolMessageType('NewFlight2', (_message.Message,), {
  'DESCRIPTOR' : _NEWFLIGHT2,
  '__module__' : 'proto.BooMan_pb2'
  # @@protoc_insertion_point(class_scope:proto.NewFlight2)
  })
_sym_db.RegisterMessage(NewFlight2)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'proto.BooMan_pb2'
  # @@protoc_insertion_point(class_scope:proto.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

_FLIGHTSANDPRICES = DESCRIPTOR.services_by_name['FlightsAndPrices']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDMESSAGE._serialized_start=29
  _IDMESSAGE._serialized_end=52
  _IDRESPONSE._serialized_start=54
  _IDRESPONSE._serialized_end=80
  _NEWFLIGHT2._serialized_start=83
  _NEWFLIGHT2._serialized_end=262
  _REGISTERRESPONSE._serialized_start=264
  _REGISTERRESPONSE._serialized_end=296
  _FLIGHTSANDPRICES._serialized_start=298
  _FLIGHTSANDPRICES._serialized_end=425
# @@protoc_insertion_point(module_scope)
