# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Discovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/Discovery.proto\x12\x05proto\"5\n\x10infoMicroservice\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"H\n\x11infoMicroservices\x12\x33\n\x12microservices_list\x18\x01 \x03(\x0b\x32\x17.proto.infoMicroservice\"J\n\x17microserviceInfoRequest\x12/\n\rmicroservices\x18\x01 \x01(\x0b\x32\x18.proto.infoMicroservices\"H\n\x15microserviceInfoReply\x12/\n\rmicroservices\x18\x01 \x01(\x0b\x32\x18.proto.infoMicroservices\"<\n\nGetRequest\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x19\n\x11serviceNameTarget\x18\x02 \x01(\t\"-\n\x08GetReply\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"/\n\nPutRequest\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"#\n\x10\x44iscoveryServers\x12\x0f\n\x07servers\x18\x01 \x03(\t\"H\n\x08PutReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12,\n\x0blist_server\x18\x02 \x01(\x0b\x32\x17.proto.DiscoveryServers2\xbe\x01\n\x10\x44iscoveryService\x12)\n\x03get\x12\x11.proto.GetRequest\x1a\x0f.proto.GetReply\x12)\n\x03put\x12\x11.proto.PutRequest\x1a\x0f.proto.PutReply\x12T\n\x14sendMicroserviceInfo\x12\x1e.proto.microserviceInfoRequest\x1a\x1c.proto.microserviceInfoReplyB\x11\n\rcontrol.protoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Discovery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcontrol.protoP\001'
  _INFOMICROSERVICE._serialized_start=32
  _INFOMICROSERVICE._serialized_end=85
  _INFOMICROSERVICES._serialized_start=87
  _INFOMICROSERVICES._serialized_end=159
  _MICROSERVICEINFOREQUEST._serialized_start=161
  _MICROSERVICEINFOREQUEST._serialized_end=235
  _MICROSERVICEINFOREPLY._serialized_start=237
  _MICROSERVICEINFOREPLY._serialized_end=309
  _GETREQUEST._serialized_start=311
  _GETREQUEST._serialized_end=371
  _GETREPLY._serialized_start=373
  _GETREPLY._serialized_end=418
  _PUTREQUEST._serialized_start=420
  _PUTREQUEST._serialized_end=467
  _DISCOVERYSERVERS._serialized_start=469
  _DISCOVERYSERVERS._serialized_end=504
  _PUTREPLY._serialized_start=506
  _PUTREPLY._serialized_end=578
  _DISCOVERYSERVICE._serialized_start=581
  _DISCOVERYSERVICE._serialized_end=771
# @@protoc_insertion_point(module_scope)
